name: Test

on: push

jobs:
  test:
    name: Install
    runs-on: macos-latest
    steps:
      - name: Install dotfiles
        run: curl https://raw.githubusercontent.com/ianjakobs/dotfiles/master/src/install.sh | sh
